#!/bin/bash

# Quick start examples for LLM QnA Bot
# Run these commands to experiment with the bot

echo "🤖 LLM QnA Bot - Quick Start Examples"
echo "======================================"
echo ""
echo "First, activate the virtual environment:"
echo "  source .venv/bin/activate"
echo ""
echo "Then run any of the examples below:"
echo ""
echo "BASIC EXAMPLES:"
echo "  # Simple question"
echo "  python -m src.main --question \"What is Python?\" --role qa"
echo ""
echo "  # With custom temperature"
echo "  python -m src.main --question \"What is AI?\" --temperature 1.2"
echo ""
echo "  # Different role"
echo "  python -m src.main --question \"Explain blockchain\" --role tutor"
echo ""
echo "COMPARISON EXAMPLES:"
echo "  # Compare temperature effects"
echo "  python -m src.main --question \"Tell a story\" --compare-temps"
echo ""
echo "  # Compare token limits"
echo "  python -m src.main --question \"What is quantum computing?\" --compare-tokens"
echo ""
echo "TOKEN & EMBEDDING EXAMPLES:"
echo "  # Analyze tokens"
echo "  python -m src.main --analyze-tokens \"Hello, how are you?\""
echo ""
echo "  # View embeddings"
echo "  python -m src.main --visualize-embeddings \"What is machine learning?\""
echo ""
echo "  # Compare multiple texts"
echo "  python -m src.main --visualize-embeddings \"AI is smart\" \"ML is powerful\" \"DL is complex\""
echo ""
echo "  # Similarity between two texts"
echo "  python -m src.main --similarity \"The cat sat on the mat\" \"A cat was sitting on a mat\""
echo ""
echo "INTERACTIVE MODE:"
echo "  # Launch interactive mode"
echo "  python -m src.main --mode interactive"
echo ""
echo "  Then try commands like:"
echo "    > ask What is machine learning?"
echo "    > role tutor"
echo "    > temp 1.5"
echo "    > visualize \"Hello world\""
echo "    > exit"
echo ""
echo "ADVANCED EXAMPLES:"
echo "  # Creative role with high temperature"
echo "  python -m src.main --question \"Write a poem about AI\" --role creative --temperature 1.8 --max-tokens 120"
echo ""
echo "  # QA with low temperature (deterministic)"
echo "  python -m src.main --question \"What is 2+2?\" --temperature 0.1"
echo ""
echo "  # Educational explanation"
echo "  python -m src.main --question \"Explain photosynthesis\" --role tutor --max-tokens 150"
echo ""
